/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.rlopez.gestform.models;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.rlopez.gestform.dao.FormationDAO;
import org.rlopez.gestform.dao.StagiaireDAO;

/**
 *
 * @author rico
 */
public class MainWindow extends javax.swing.JFrame {

    StagiaireTableModel stm;
    FormationTableModel ftm;
    EcfTableModel etm;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {

        initComponents();
        this.setLocationRelativeTo(null);

        List<Formation> formations = FormationDAO.findAllFormation();
        for (Formation f : formations) {
            comboFormations.addItem(f);
        }
        jPanelEditStagiaire.setVisible(false);
        btnSupprFormation.setEnabled(false);
        btnAjouterFormation.setEnabled(false);
        btnClearAdd.setEnabled(false);
        btnAddStagiaire.setEnabled(false);
        btnSupprimerStagiaire.setEnabled(false);

        tblStagiaire.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent evt) {
                btnSupprimerStagiaire.setEnabled(true);
                int index = tblStagiaire.getSelectedRow(); // On récupère le numéro de la ligne sélectionnée
                if (index > -1) {
                    Stagiaire sta = stm.getStagiaire(index); //On récupère le stagiaire en fonction du numéro de ligne dans le model
                    jPanelEditStagiaire.setVisible(true);
                    fieldEditMatricule.setText(String.valueOf(sta.getMatricule()));
                    fieldEditNom.setText(sta.getNom());
                    fieldEditPrenom.setText(sta.getPrenom());
                    //                editComboFormations.setSelectedItem(sta.getFormation());

                    editComboFormations.removeAllItems();
                    for (Formation f : formations) {
                        editComboFormations.addItem(f);
                    }

                    Formation curForm = sta.getFormation();
                    editComboFormations.setSelectedItem(curForm);
                }

            }

        });
        
                tblFormation.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent evt) {
            btnSupprFormation.setEnabled(true);
            }

        });
                

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFormation = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnAjouterFormation = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fieldAddFormation = new javax.swing.JTextField();
        btnSupprFormation = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStagiaire = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnAddStagiaire = new javax.swing.JButton();
        fieldAddMatricule = new javax.swing.JTextField();
        fieldAddNom = new javax.swing.JTextField();
        jLabelAddMatricule = new javax.swing.JLabel();
        jLabelAddNom = new javax.swing.JLabel();
        fieldAddPrenom = new javax.swing.JTextField();
        jLabelAddPrenom = new javax.swing.JLabel();
        jLabelAddFormation = new javax.swing.JLabel();
        comboFormations = new javax.swing.JComboBox<>();
        btnClearAdd = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jPanelEditStagiaire = new javax.swing.JPanel();
        jLabelEditMatricule = new javax.swing.JLabel();
        fieldEditMatricule = new javax.swing.JTextField();
        jLabelEditNom = new javax.swing.JLabel();
        fieldEditNom = new javax.swing.JTextField();
        jLabelEditPrenom = new javax.swing.JLabel();
        fieldEditPrenom = new javax.swing.JTextField();
        jLabelEditFormation = new javax.swing.JLabel();
        editComboFormations = new javax.swing.JComboBox<>();
        btnEditStagiaire = new javax.swing.JButton();
        btnSupprimerStagiaire = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jScrollPane1.setViewportView(tblFormation);
        ftm = new FormationTableModel(FormationDAO.findAllFormation());
        tblFormation.setModel(ftm);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajouter une formation"));

        btnAjouterFormation.setText("Ajouter");
        btnAjouterFormation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterFormationActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom");

        fieldAddFormation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldAddFormationMouseClicked(evt);
            }
        });
        fieldAddFormation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAddFormationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(fieldAddFormation, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(btnAjouterFormation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldAddFormation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnAjouterFormation)
                .addContainerGap())
        );

        btnSupprFormation.setText("Supprimer la formation");
        btnSupprFormation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprFormationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSupprFormation, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSupprFormation)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Liste des formations", jPanel1);

        jScrollPane2.setViewportView(tblStagiaire);
        stm = new StagiaireTableModel(StagiaireDAO.findAllStagiaire());
        tblStagiaire.setModel(stm);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajouter un stagiaire"));

        btnAddStagiaire.setText("Ajouter");
        btnAddStagiaire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddStagiaireMouseClicked(evt);
            }
        });
        btnAddStagiaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStagiaireActionPerformed(evt);
            }
        });

        fieldAddMatricule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldAddMatriculeMouseClicked(evt);
            }
        });

        fieldAddNom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldAddNomMouseClicked(evt);
            }
        });

        jLabelAddMatricule.setText("Matricule");

        jLabelAddNom.setText("Nom");

        fieldAddPrenom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldAddPrenomMouseClicked(evt);
            }
        });

        jLabelAddPrenom.setText("Prénom");

        jLabelAddFormation.setText("Formation");

        btnClearAdd.setText("RAZ");
        btnClearAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAddMatricule)
                            .addComponent(jLabelAddNom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldAddNom)
                            .addComponent(fieldAddMatricule, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAddPrenom)
                            .addComponent(jLabelAddFormation))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldAddPrenom)
                            .addComponent(comboFormations, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClearAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddStagiaire)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldAddMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelAddMatricule))
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAddNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAddPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddPrenom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddFormation)
                    .addComponent(comboFormations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStagiaire)
                    .addComponent(btnClearAdd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelEditStagiaire.setBorder(javax.swing.BorderFactory.createTitledBorder("Editer un stagiaire"));

        jLabelEditMatricule.setText("Matricule");

        jLabelEditNom.setText("Nom");

        jLabelEditPrenom.setText("Prénom");

        jLabelEditFormation.setText("Formation");

        btnEditStagiaire.setText("Mettre à jour");
        btnEditStagiaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStagiaireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEditStagiaireLayout = new javax.swing.GroupLayout(jPanelEditStagiaire);
        jPanelEditStagiaire.setLayout(jPanelEditStagiaireLayout);
        jPanelEditStagiaireLayout.setHorizontalGroup(
            jPanelEditStagiaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditStagiaireLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditStagiaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEditStagiaireLayout.createSequentialGroup()
                        .addGroup(jPanelEditStagiaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEditMatricule)
                            .addComponent(jLabelEditNom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelEditStagiaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldEditNom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldEditMatricule, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEditStagiaireLayout.createSequentialGroup()
                        .addGroup(jPanelEditStagiaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEditPrenom)
                            .addComponent(jLabelEditFormation))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanelEditStagiaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editComboFormations, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldEditPrenom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEditStagiaireLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditStagiaire)))
                .addContainerGap())
        );
        jPanelEditStagiaireLayout.setVerticalGroup(
            jPanelEditStagiaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditStagiaireLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditStagiaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEditMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEditMatricule))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditStagiaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEditNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEditNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditStagiaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEditPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEditPrenom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditStagiaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEditFormation)
                    .addComponent(editComboFormations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnEditStagiaire)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSupprimerStagiaire.setText("Supprimer le stagiaire");
        btnSupprimerStagiaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerStagiaireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEditStagiaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(btnSupprimerStagiaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSupprimerStagiaire))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelEditStagiaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Liste des stagiaires", jPanel2);

        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ECF", jPanel5);

        jMenu1.setText("Fichier");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Ajouter une formation");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Ajouter un stagiaire");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem2.setText("Quitter");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edition");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("?");

        jMenuItem1.setText("A propos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterFormationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterFormationActionPerformed

        try {
            String ajoutFormation = fieldAddFormation.getText();
            Formation f = new Formation(ajoutFormation);
            
            FormationDAO.ajoutFormation(f);
            
            ftm.addFormation(f);
        } catch (Exception ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        


    }//GEN-LAST:event_btnAjouterFormationActionPerformed

    private void btnAddStagiaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStagiaireActionPerformed

        String nomStagiaire = fieldAddNom.getText();
        String prenomStagiaire = fieldAddPrenom.getText();
        String matriculeStagiaire = fieldAddMatricule.getText();
        int strMatriculeStagiaire = Integer.parseInt(matriculeStagiaire);
        Object listeFormation = comboFormations.getSelectedItem();

        Formation formation = (Formation) listeFormation;

        try {
            Stagiaire sta = new Stagiaire(1, nomStagiaire, prenomStagiaire, strMatriculeStagiaire, formation);
            StagiaireDAO.save(sta);
            stm.addStagiaire(sta);
        } catch (Exception e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }

        fieldAddNom.setText(null);
        fieldAddPrenom.setText(null);
        fieldAddMatricule.setText(null);


    }//GEN-LAST:event_btnAddStagiaireActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane jop1;
        jop1 = new JOptionPane();
        jop1.showMessageDialog(null, "By Rico", "A propos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
//        String ajoutFormation = JOptionPane.showInputDialog(null, "Entrez la formation : ", "Formation", JOptionPane.QUESTION_MESSAGE);
//        FormationDAO.insertFormation(ajoutFormation);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        String prenomStagiaire = JOptionPane.showInputDialog(null, "Entrez le prenom", "Ajout du prénom", JOptionPane.QUESTION_MESSAGE); // Création boite de dialogue
        String nomStagiaire = JOptionPane.showInputDialog(null, "Entrez le nom", "Ajout du Nom", JOptionPane.QUESTION_MESSAGE);
        String StrmatriculeStagiaire = JOptionPane.showInputDialog(null, "Matricule", "Ajout du  Matricule", JOptionPane.QUESTION_MESSAGE);
        int matriculeStagiaire = Integer.parseInt(StrmatriculeStagiaire);

        List<Formation> objetFormation = FormationDAO.findAllFormation(); // Création d'une nouvelle liste Formation qui appelle la méthode findAllFormation qui récupère la liste des formations
        Object[] tblFormation = objetFormation.toArray(); // On met le résultat de la liste sous forme de tableau
        Object listeFormation = JOptionPane.showInputDialog(null, "Choisir la formation", "Liste", JOptionPane.QUESTION_MESSAGE, null, tblFormation, tblFormation[2]);

        Formation formation = (Formation) listeFormation;

        try {
            StagiaireDAO.save(new Stagiaire(1, nomStagiaire, prenomStagiaire, matriculeStagiaire, formation));
        } catch (Exception e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnEditStagiaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStagiaireActionPerformed
        int index = tblStagiaire.getSelectedRow();
        Stagiaire s = stm.getStagiaire(index);
        s.setNom(fieldEditNom.getText());
        s.setPrenom(fieldEditPrenom.getText());
        //s.setMatricule();

        try {
            StagiaireDAO.updateStagiaire(s);
            stm.fireTableRowsUpdated(index, index);
            fieldEditMatricule.setText(null);
            fieldEditPrenom.setText(null);
            fieldEditNom.setText(null);

        } catch (Exception e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
    }//GEN-LAST:event_btnEditStagiaireActionPerformed

    private void btnSupprFormationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprFormationActionPerformed
        int index = tblFormation.getSelectedRow();
        Formation f = ftm.getFormation(index);
        FormationDAO.supprimerFormation(f);
        ftm.delFormation(f);
        
        

//        int ligne = TableauStagiaire.getSelectedRow();
//        if (ligne > -1) {
//            Stagiaire s = tbls.getStagiaire(ligne);
//            try {
//                StagiaireDao.delete(s);
//                tbls.delStagiaire(s);
//                btnDelStag.setEnabled(true);
//            } catch (Exception ex) {
//                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
//            }


    }//GEN-LAST:event_btnSupprFormationActionPerformed

    private void fieldAddFormationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldAddFormationMouseClicked
        btnAjouterFormation.setEnabled(true);
    }//GEN-LAST:event_fieldAddFormationMouseClicked

    private void btnSupprimerStagiaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerStagiaireActionPerformed
        int index = tblStagiaire.getSelectedRow();
        Stagiaire s = stm.getStagiaire(index);
        
        StagiaireDAO.supprimerStagiaire(s);
        stm.delStagiaire(s);
        
        
    }//GEN-LAST:event_btnSupprimerStagiaireActionPerformed

    private void fieldAddFormationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAddFormationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAddFormationActionPerformed

    private void btnAddStagiaireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddStagiaireMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddStagiaireMouseClicked

    private void fieldAddMatriculeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldAddMatriculeMouseClicked
        btnClearAdd.setEnabled(true);
        btnAddStagiaire.setEnabled(true);
    }//GEN-LAST:event_fieldAddMatriculeMouseClicked

    private void fieldAddNomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldAddNomMouseClicked
        btnClearAdd.setEnabled(true);
        btnAddStagiaire.setEnabled(true);
    }//GEN-LAST:event_fieldAddNomMouseClicked

    private void fieldAddPrenomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldAddPrenomMouseClicked
        btnClearAdd.setEnabled(true);
        btnAddStagiaire.setEnabled(true);
    }//GEN-LAST:event_fieldAddPrenomMouseClicked

    private void btnClearAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAddActionPerformed
        fieldAddNom.setText(null);
        fieldAddPrenom.setText(null);
        fieldAddMatricule.setText(null);
    }//GEN-LAST:event_btnClearAddActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStagiaire;
    private javax.swing.JButton btnAjouterFormation;
    private javax.swing.JButton btnClearAdd;
    private javax.swing.JButton btnEditStagiaire;
    private javax.swing.JButton btnSupprFormation;
    private javax.swing.JButton btnSupprimerStagiaire;
    private javax.swing.JComboBox<Formation> comboFormations;
    private javax.swing.JComboBox<Formation> editComboFormations;
    private javax.swing.JTextField fieldAddFormation;
    private javax.swing.JTextField fieldAddMatricule;
    private javax.swing.JTextField fieldAddNom;
    private javax.swing.JTextField fieldAddPrenom;
    private javax.swing.JTextField fieldEditMatricule;
    private javax.swing.JTextField fieldEditNom;
    private javax.swing.JTextField fieldEditPrenom;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAddFormation;
    private javax.swing.JLabel jLabelAddMatricule;
    private javax.swing.JLabel jLabelAddNom;
    private javax.swing.JLabel jLabelAddPrenom;
    private javax.swing.JLabel jLabelEditFormation;
    private javax.swing.JLabel jLabelEditMatricule;
    private javax.swing.JLabel jLabelEditNom;
    private javax.swing.JLabel jLabelEditPrenom;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelEditStagiaire;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblFormation;
    private javax.swing.JTable tblStagiaire;
    // End of variables declaration//GEN-END:variables
}
